server:
  port: 8081

spring:
  profiles:
    active: @config.profiles.active@
  application:
    name: blogroom-console

eureka:
  client:
    serviceUrl:
      defaultZone: http://@config.eureka.ip@:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}


logging:
  config:
    classpath:logback-spring.xml

author:
  name: qiuyunduo