spring:
  profiles:
    active: dev
  application:
    name: blogroom-console


server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

User: qiuyunduo

logging:
  config:
    classpath:logback-spring.xml

