spring:
  profiles:
    active: dev
  application:
    name: article-provider


server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

logging:
  config:
    classpath: logback-spring.xml

