server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
spring:
  application:
    name: server-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        ssl:
          useInsecureTrustManager: true
          handshake-timeout-millis: 10000
          close-notify-flush-timeout-millis: 3000
          close-notify-read-timeout-millis: 0
      routes:
        #用户信息关服务
        - id: user-service
          uri: lb://user-provider
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        #博客空间相关服务
        - id: blog-service
          uri: lb://blog-provider
          predicates:
           - Path=/blog/**
          filters:
           - StripPrefix=1
        #博客文章相关服务
        - id: article-service
          uri: lb://article-provider
          predicates:
          - Path=/article/**
          filters:
           - StripPrefix=1
        #网站相关服务
        - id: website-service
          uri: lb://website-provider
          predicates:
           - Path=/website/**
          filters:
           - StripPrefix=1