spring:
  profiles:
    active: dev
  application:
    name: user-provider


server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

user:
  default:
    headImage: http://localhost:9000/static/images/default.jpg

logging:
  config:
    classpath: logback-spring.xml


