spring:
  profiles:
    active: @config.profiles.active@
  application:
    name: website-provider


server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://@config.eureka.ip@:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

logging:
  config:
    classpath:logback-spring.xml

